name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 8, 10, 12, 14, 16, 18, 20 ]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install
      - run: npm run build
      - run: npm run test:ci

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@master
        env:
          COVERALLS_FLAG_NAME: run-${{ matrix.node-version }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
